# Generated by Django 4.2.6 on 2024-02-28 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carisma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='Employee_mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^\\d{10}$', message='Mobile number must be exactly 10 digits')]),
        ),
    ]
